# Generated by Django 2.2.3 on 2019-07-10 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_area', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.PositiveIntegerField()),
                ('target_date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feature_request.Client')),
                ('product_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feature_request.ProductArea')),
            ],
            options={
                'verbose_name_plural': 'requests',
                'ordering': ['-priority'],
            },
        ),
    ]
