# Generated by Django 2.2.3 on 2019-07-09 14:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('client', models.CharField(choices=[('Client A', 'A'), ('Client B', 'B'), ('Client C', 'C')], default='Client A', max_length=10)),
                ('priority', models.PositiveIntegerField()),
                ('target_date', models.DateField(default=datetime.datetime(2019, 7, 9, 14, 39, 44, 704015, tzinfo=utc))),
                ('product_area', models.CharField(choices=[('Assessments', 'Assessments'), ('Billing', 'Billing'), ('Recruit', 'Recruit'), ('Reports', 'Reports')], default='Assessments', max_length=20)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
