# Generated by Django 2.2.3 on 2019-07-10 12:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_area', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('client', models.CharField(choices=[('Client A', 'A'), ('Client B', 'B'), ('Client C', 'C')], default='Client A', max_length=10)),
                ('priority', models.PositiveIntegerField()),
                ('target_date', models.DateField(default=datetime.datetime(2019, 7, 10, 12, 42, 35, 382068, tzinfo=utc))),
                ('product_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feature_request.ProductArea')),
            ],
            options={
                'verbose_name_plural': 'requests',
            },
        ),
    ]
