# Generated by Django 2.2.3 on 2019-07-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='client',
            field=models.CharField(choices=[('Client A', 'A'), ('Client B', 'B'), ('Client C', 'C')], default='Client A', max_length=10),
        ),
    ]
