# Generated by Django 2.2.3 on 2019-07-09 14:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('feature_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='target_date',
            field=models.DateField(default=datetime.datetime(2019, 7, 9, 14, 39, 54, 32880, tzinfo=utc)),
        ),
    ]
