# Generated by Django 2.2.3 on 2019-07-11 00:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feature_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productarea',
            options={'verbose_name': 'Product Area'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={},
        ),
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
