# Generated by Django 2.2.3 on 2019-07-10 14:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('feature_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-priority'], 'verbose_name_plural': 'requests'},
        ),
        migrations.AlterField(
            model_name='request',
            name='target_date',
            field=models.DateField(default=datetime.datetime(2019, 7, 10, 14, 27, 50, 305974, tzinfo=utc)),
        ),
    ]
