# Generated by Django 2.2.3 on 2019-07-10 14:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('feature_request', '0002_auto_20190710_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='target_date',
            field=models.DateField(default=datetime.datetime(2019, 7, 10, 14, 58, 41, 72643, tzinfo=utc)),
        ),
    ]
