# Generated by Django 2.2.3 on 2019-07-09 15:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('feature_request', '0002_auto_20190709_2239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name_plural': 'requests'},
        ),
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='target_date',
            field=models.DateField(default=datetime.datetime(2019, 7, 9, 15, 29, 38, 824553, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='request',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
