# Generated by Django 2.2.3 on 2019-07-11 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature_request', '0002_auto_20190711_0838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['client']},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['priority']},
        ),
    ]
