# Generated by Django 2.2.3 on 2019-07-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_request', '0002_auto_20190708_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='target_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
