# Generated by Django 2.2.3 on 2019-07-09 16:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('feature_request', '0003_auto_20190709_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='target_date',
            field=models.DateField(default=datetime.datetime(2019, 7, 9, 16, 8, 20, 324400, tzinfo=utc)),
        ),
    ]
