# Generated by Django 2.2.3 on 2019-07-09 16:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('feature_request', '0004_auto_20190710_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='order',
        ),
        migrations.AlterField(
            model_name='request',
            name='target_date',
            field=models.DateField(default=datetime.datetime(2019, 7, 9, 16, 9, 28, 861748, tzinfo=utc)),
        ),
    ]
